### PR TITLE
DMG for Macs

### PR DESCRIPTION
**Pull request by SoPat712**
This commit creates a DMG which can be added to the release folder. It does not install guiscrcpy, but simply creates a simple .app file for ease of access. No special features come with this.

I will make a better version of this eventually, which automatically installs guiscrcpy if it's not installed, and runs guiscrcpy if it is installed, but I threw this together in the matter of minutes specifically for my use case.

### CODE REVIEW

**Comment by srevinsaju** [comment]
@SoPat712 Could you explain how you created the dmg? And add the steps to the documentation too?

**Comment by SoPat712** [comment]
Yes, I can. I created an apple script that runs a command `do shell script "/usr/local/bin/guiscrcpy"`, and then exported the apple script to .app by hitting file, then export, then choosing application in the drop-down. I also selected the logo for guiscrcpy and added it to the .app file created by hitting get info, and pasting it into where the icon goes. Now, all there was to do was to use an app called dropdmg, which creates dmgs using preset layouts and allowed me to also create the applications folder alias in the dmg. I will add this to the README in just a minute.

**Comment by srevinsaju** [comment]
But, a `python` interpreter does not get embedded into the dmg right?

**Comment by srevinsaju** [comment]
How is the file size so small, `+780 KB` only? guiscrcpy alone take 11 MB, and python takes another 28 MB. Do you mean the `dmg` is not standalone?

**Comment by SoPat712** [comment]
No, not at all. It merely runs the Unix executable. It's convenience. If people feel uncomfortable with me creating the app, I can put together a step by step guide with pictures that allows them to make the app themselves.

**Comment by SoPat712** [comment]
And yes, it is not standalone. It still requires that you download guiscrcpy using pip3 before using it. I stated that in my 2nd version of the app, I will have it download it for you, but this currently does nothing but run commands and there is no code per se that runs, other than whatever apple deems necessary to create an app.

**Comment by srevinsaju** [comment]
I see, so the `dmg` in mac os, like a shortcut to the app? Thanks. I did not know of that. 

Few of my curious questions:
* Does it require installing xcode / development tools?
* will the script automatically download and install pyhton
* will the script only `pip` install it?
* does the script have any interaction with `homebrew` or any other thirdpart products which are not available with default macOS system?

**Comment by SoPat712** [comment]
Would it be possible to take this conversation to discord? I find it inconvenient to add images on GitHub threads.

**Comment by srevinsaju** [comment]
Yes, I am mostly online :smile:

**Comment by SoPat712** [comment]
Alright, my discord tag is Intellijence#3188

**Comment by srevinsaju** [comment]
Ah, we have a `guiscrcpy` discord channel :smile:

**Pull request closed without merging**
